import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { config } from "./config.js";
import { BrowserSession } from "./browser.js";
import { AiStudioProvider } from "./providers/aistudio.js";
import { GeminiAppProvider } from "./providers/gemini-app.js";
import type { CaptureResult, GenerateRequest } from "./providers/shared.js";
import { SerialQueue } from "./queue.js";
import { saveImage, type SavedImage } from "./storage.js";
import { mimeFor, readDimensions, sniffFormat } from "./imagebytes.js";
import {
  describeCrop,
  parseCropSpec,
  resolveCropRect,
  type CropRect,
  type CropSpec,
} from "./crop.js";
import { describeError, BananaError } from "./errors.js";
import { hasQuota, markRemoteExhausted, quotaStatus, recordUsage } from "./state.js";

type TextContent = { type: "text"; text: string };
type ImageContent = { type: "image"; data: string; mimeType: string };
type ToolResult = { content: (TextContent | ImageContent)[]; isError?: boolean };

/** The seams the tools depend on, so tests can drive the server without a browser. */
export interface ImageProvider {
  generate(request: GenerateRequest): Promise<CaptureResult>;
  ensureReady(): Promise<unknown>;
}

export interface ImageOps {
  readonly isOpen: boolean;
  makePreview(buf: Buffer, mimeType: string): Promise<string | null>;
  cropImage(buf: Buffer, mimeType: string, rect: CropRect): Promise<Buffer | null>;
}

export interface ServerDeps {
  provider: ImageProvider;
  session: ImageOps;
  queue: SerialQueue;
}

/** Picks the web surface named by BANANA_PROVIDER. */
export function createProvider(session: BrowserSession): ImageProvider {
  return config.provider === "aistudio" ? new AiStudioProvider(session) : new GeminiAppProvider(session);
}

function defaultDeps(): ServerDeps {
  const session = new BrowserSession();
  return {
    session,
    provider: createProvider(session),
    queue: new SerialQueue(config.pacingMs),
  };
}

/**
 * Travels with every successful result. Cropping removes a visible mark but not
 * SynthID, so an agent handing the file onward should still know what it is.
 */
const PROVENANCE_NOTE =
  "Provenance: AI-generated by Gemini; contains an invisible SynthID watermark.";

/**
 * Said only when no crop ran on a surface that stamps a visible mark. An agent that
 * cannot see the mark would otherwise pass a logo-stamped image straight into a
 * document, so tell it the mark is there and exactly how to remove it.
 */
const WATERMARK_WARNING =
  'Visible watermark: Gemini stamped its sparkle logo in the bottom-right corner. ' +
  'To remove it losslessly, re-run with crop:"auto" (trims 10% off the right edge), or ' +
  "crop the image yourself before using it.";

/** Surfaces known to composite a visible mark into the delivered image. */
function stampsVisibleMark(): boolean {
  return config.provider === "gemini-app";
}

/**
 * Runs a generation, refusing rather than queuing when one is already in flight.
 *
 * Queuing looked harmless but wasn't: one generation takes ~20s (an edit ~30s), so a
 * third caller waited ~45s before starting and blew past the MCP client's default 60s
 * request timeout while the server was working perfectly. Failing fast with a clear
 * "wait" is honest; a silent queue that times out is not.
 *
 * The depth check and queue.run() are both synchronous, so no second caller can slip
 * between them.
 */
function runExclusive(deps: ServerDeps, job: () => Promise<ToolResult>): Promise<ToolResult> {
  if (deps.queue.depth > 0) return Promise.resolve(errorResult(BananaError.busy()));
  return deps.queue.run(job).catch(async (err) => {
    // Google's own limit is authoritative: remember it so later calls fail fast instead
    // of driving a browser to be told no again.
    // Only Google's refusal is authoritative; the local counter running out must not
    // latch the day closed, or one bad BANANA_DAILY_LIMIT would lock the tool out.
    if (err instanceof BananaError && err.remoteQuota) {
      await markRemoteExhausted().catch(() => {});
    }
    return errorResult(err);
  });
}

function errorResult(err: unknown): ToolResult {
  const info = describeError(err);
  const lines = [`[${info.kind}] ${info.message}`];
  if (info.hint) lines.push(`Hint: ${info.hint}`);
  if (info.debugPath) lines.push(`Debug dump: ${info.debugPath}`);
  return { content: [{ type: "text", text: lines.join("\n") }], isError: true };
}

function describeSaved(saved: SavedImage[]): string {
  return saved
    .map((image, index) => {
      const dims = image.width && image.height ? `${image.width}x${image.height}` : "unknown size";
      return `${index + 1}. ${image.path} (${dims}, ${image.format}, ${Math.round(image.bytes / 1024)} KB)`;
    })
    .join("\n");
}

/**
 * Trims the requested inset off an image, re-encoding losslessly as PNG. A crop that
 * cannot be performed leaves the image untouched and says so, rather than losing it.
 */
async function applyCrop(
  deps: ServerDeps,
  buf: Buffer,
  spec: CropSpec | null,
  notes: string[],
): Promise<{ image: Buffer; cropped: boolean }> {
  if (!spec) return { image: buf, cropped: false };

  const format = sniffFormat(buf);
  const dims = readDimensions(buf);
  if (!format || !dims) {
    notes.push("Crop skipped: could not read image dimensions.");
    return { image: buf, cropped: false };
  }

  let rect: CropRect | null;
  try {
    rect = resolveCropRect(spec, dims.width, dims.height);
  } catch (err) {
    throw BananaError.invalidInput(err instanceof Error ? err.message : String(err));
  }
  if (!rect) {
    notes.push("Crop resolved to zero pixels; image left unchanged.");
    return { image: buf, cropped: false };
  }

  const cropped = await deps.session.cropImage(buf, mimeFor(format), rect);
  if (!cropped) {
    notes.push("Crop failed in the browser; saved the uncropped image instead.");
    return { image: buf, cropped: false };
  }
  notes.push(`Crop: ${describeCrop(rect, dims)}.`);
  return { image: cropped, cropped: true };
}

async function runGeneration(
  deps: ServerDeps,
  args: {
    prompt: string;
    count: number;
    aspectRatio?: string;
    imagePaths?: string[];
    outputPath?: string;
    inline: boolean;
    reuseConversation: boolean;
    crop?: string;
  },
): Promise<ToolResult> {
  // Parsed before the generation so a typo costs no quota.
  let cropSpec: CropSpec | null;
  try {
    cropSpec = parseCropSpec(args.crop ?? config.crop);
  } catch (err) {
    throw BananaError.invalidInput(err instanceof Error ? err.message : String(err));
  }

  if (!(await hasQuota(args.count))) {
    const { used, limit } = await quotaStatus();
    throw BananaError.quotaExhausted(used, limit);
  }

  const { images, text } = await deps.provider.generate({
    prompt: args.prompt,
    count: args.count,
    aspectRatio: args.aspectRatio,
    imagePaths: args.imagePaths,
    reuseConversation: args.reuseConversation,
  });

  const notes: string[] = [];
  const finalImages: Buffer[] = [];
  // Warn unless EVERY image actually got cropped. A requested crop that silently bailed
  // out — unreadable dimensions, a browser failure, a spec resolving to zero pixels —
  // leaves the mark in place, and gating on the parsed spec would hide exactly that.
  let allCropped = images.length > 0;
  for (const buf of images) {
    const result = await applyCrop(deps, buf, cropSpec, notes);
    finalImages.push(result.image);
    if (!result.cropped) allCropped = false;
  }

  const saved: SavedImage[] = [];
  for (const [index, buf] of finalImages.entries()) {
    saved.push(
      await saveImage(buf, args.prompt, {
        outputPath: args.outputPath,
        index,
        total: finalImages.length,
      }),
    );
  }
  await recordUsage(images.length);
  const quota = await quotaStatus();

  const content: (TextContent | ImageContent)[] = [
    {
      type: "text",
      text: [
        `Generated ${saved.length} image${saved.length === 1 ? "" : "s"}:`,
        describeSaved(saved),
        notes.length > 0 ? notes.join("\n") : null,
        !allCropped && stampsVisibleMark() ? WATERMARK_WARNING : null,
        PROVENANCE_NOTE,
        `Quota (local estimate): ${quota.used}/${quota.limit} used today, ${quota.remaining} left.`,
        text ? `Model said: ${text.slice(0, 300)}` : null,
      ]
        .filter(Boolean)
        .join("\n"),
    },
  ];

  // Full-size base64 only on request; otherwise a small preview so the calling
  // model can see the result without megabytes of context.
  for (const [index, buf] of finalImages.entries()) {
    const format = saved[index]!.format;
    if (args.inline) {
      content.push({ type: "image", data: buf.toString("base64"), mimeType: mimeFor(format) });
      continue;
    }
    const preview = await deps.session.makePreview(buf, mimeFor(format));
    if (preview) content.push({ type: "image", data: preview, mimeType: "image/jpeg" });
  }

  return { content };
}

export function createServer(deps: ServerDeps = defaultDeps()): McpServer {
  const server = new McpServer(
    { name: "banana-bridge", version: "0.1.0" },
    {
      instructions:
        "Generates images with Gemini by driving its web UI in a real browser. " +
        "Requires a one-time `npx banana-bridge login`. " +
        "ONE REQUEST AT A TIME: a generation takes roughly 20 seconds (an edit roughly 30). If one " +
        "is already running, another call returns a `busy` error immediately rather than waiting — " +
        "wait for the first to finish instead of retrying. Do not issue generate/edit calls in " +
        "parallel. `session_status` always answers, even while busy. " +
        "Quota is limited: `quota_exhausted` means the daily ceiling is reached (either the local " +
        "estimate or Google's own limit, which is authoritative) and further calls will keep " +
        "failing until it resets, so stop retrying. " +
        "All images returned by this server are AI-generated and carry Google's SynthID, an " +
        "invisible in-pixel watermark that survives cropping, resizing and re-encoding. Preserve " +
        "that provenance if you pass these images on. Images also carry a VISIBLE Gemini logo in " +
        'the bottom-right corner unless you pass crop:"auto"; each result says which applies.',
    },
  );

  server.registerTool(
    "generate_image",
    {
      title: "Generate image",
      description:
        "Generate an image from a text prompt by driving Gemini's web UI in a real browser. " +
        "Saves to disk and returns the file path plus a small preview. Takes roughly 20 seconds. " +
        "Only one generation runs at a time: if one is in flight this returns `busy` immediately, " +
        "so wait rather than retrying. Returns `quota_exhausted` when the daily limit is reached. " +
        "Output is AI-generated and carries an invisible SynthID watermark.",
      inputSchema: {
        prompt: z.string().min(1).describe("What to draw. Be specific about subject, style and composition."),
        aspect_ratio: z
          .enum(["1:1", "3:4", "4:3", "9:16", "16:9"])
          .optional()
          .describe("Requested aspect ratio; passed to the model as part of the prompt."),
        count: z.number().int().min(1).max(4).default(1).describe("How many images to ask for (1-4)."),
        output_path: z.string().optional().describe("Absolute path to write to. Defaults to the configured output dir."),
        inline: z
          .boolean()
          .default(false)
          .describe("Return the full-resolution image as base64 instead of a downscaled preview."),
        crop: z
          .string()
          .optional()
          .describe(
            'Removes the visible Gemini watermark, losslessly. Gemini stamps a sparkle logo ' +
              'in the bottom-right corner of every image; "auto" trims 10% off the right edge, ' +
              'which clears it. Also accepts "bottom:6%", "48px", or "top,right,bottom,left". ' +
              'Defaults to BANANA_CROP (off), in which case the result says the mark is present.',
          ),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async (args): Promise<ToolResult> =>
      runExclusive(deps, () =>
        runGeneration(deps, {
          prompt: args.prompt,
          count: args.count ?? 1,
          aspectRatio: args.aspect_ratio,
          outputPath: args.output_path,
          inline: args.inline ?? false,
          crop: args.crop,
          reuseConversation: false,
        }),
      ),
  );

  server.registerTool(
    "edit_image",
    {
      title: "Edit image",
      description:
        "Edit or combine existing local images with a text instruction. The images are attached to " +
        "Gemini's chat and the edited result is saved to disk. Takes roughly 30 seconds. Only one " +
        "request runs at a time: if one is in flight this returns `busy` immediately, so wait rather " +
        "than retrying. Attachment is verified before the prompt is sent, so a failed upload raises " +
        "upload_unsupported instead of silently returning an unrelated image. Output is AI-generated " +
        "and carries an invisible SynthID watermark.",
      inputSchema: {
        prompt: z.string().min(1).describe("The edit instruction, e.g. 'make the sky stormy'."),
        image_paths: z
          .array(z.string())
          .min(1)
          .max(4)
          .describe("Absolute paths of local images to upload as input."),
        output_path: z.string().optional().describe("Absolute path to write the result to."),
        inline: z.boolean().default(false).describe("Return full-resolution base64 instead of a preview."),
        crop: z
          .string()
          .optional()
          .describe(
            'Removes the visible Gemini watermark, losslessly. Gemini stamps a sparkle logo ' +
              'in the bottom-right corner of every image; "auto" trims 10% off the right edge, ' +
              'which clears it. Also accepts "bottom:6%", "48px", or "top,right,bottom,left". ' +
              'Defaults to BANANA_CROP (off), in which case the result says the mark is present.',
          ),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async (args): Promise<ToolResult> =>
      runExclusive(deps, () =>
        runGeneration(deps, {
          prompt: args.prompt,
          count: 1,
          imagePaths: args.image_paths,
          outputPath: args.output_path,
          inline: args.inline ?? false,
          crop: args.crop,
          reuseConversation: false,
        }),
      ),
  );

  server.registerTool(
    "session_status",
    {
      title: "Session status",
      description:
        "Report whether a generation is currently running, whether the browser session is signed in, " +
        "and the daily-quota estimate. Always answers immediately, even while a generation is in " +
        "flight — use it to check before starting another request.",
      inputSchema: {},
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    async (): Promise<ToolResult> => {
      const quota = await quotaStatus();
      const lines: string[] = [];
      const trailing: string[] = [];

      // Never queue behind a generation: this tool exists partly to tell the caller that
      // one is running, which is useless if it blocks until that finishes.
      if (deps.queue.depth > 0) {
        lines.push("BUSY: a generation is in progress. Wait for it to finish before starting another.");
        lines.push("Signed in: yes (a generation is running, so the session is live)");
      } else {
        try {
          await deps.queue.run(() => deps.provider.ensureReady());
          lines.push("Signed in: yes");
        } catch (err) {
          const info = describeError(err);
          const brief = info.message.split("\n")[0]!.slice(0, 200);
          lines.push(`Signed in: no (${info.kind}: ${brief})`);
          if (info.hint) trailing.push(`Hint: ${info.hint}`);
        }
      }

      lines.push(
        `Browser: ${deps.session.isOpen ? "running" : "not started"} ` +
          `(headless=${config.headless}${config.hasDisplay ? "" : ", no display detected"})`,
        `Provider: ${config.provider}` +
          (config.providerInvalid ? ` (ignored invalid BANANA_PROVIDER="${config.providerInvalid}")` : ""),
        `Model: ${config.model}`,
        `Profile: ${config.profileDir}`,
        `Output dir: ${config.outputDir}`,
        `Default crop: ${config.crop}`,
        `Quota (local estimate): ${quota.used}/${quota.limit} used on ${quota.day}, ${quota.remaining} left.` +
          (quota.corrupt ? " [state file was unreadable and has been reset — the count may be low]" : ""),
        ...(quota.remoteExhausted
          ? [
              "QUOTA EXHAUSTED: Google itself refused for exceeding its limit today. Further " +
                "generate/edit calls will fail until it resets.",
            ]
          : []),
        `Queue depth: ${deps.queue.depth}`,
        ...trailing,
      );
      return { content: [{ type: "text", text: lines.join("\n") }] };
    },
  );

  return server;
}

export async function serve(): Promise<void> {
  const session = new BrowserSession();
  const deps: ServerDeps = {
    session,
    provider: createProvider(session),
    queue: new SerialQueue(config.pacingMs),
  };
  const server = createServer(deps);
  const transport = new StdioServerTransport();
  await server.connect(transport);

  const shutdown = async () => {
    await session.close();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  process.stdin.on("close", shutdown);
}
