import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { config } from "./config.js";
import { BrowserSession } from "./browser.js";
import { AiStudioProvider, type CaptureResult, type GenerateRequest } from "./providers/aistudio.js";
import { SerialQueue } from "./queue.js";
import { saveImage, type SavedImage } from "./storage.js";
import { mimeFor, readDimensions, sniffFormat } from "./imagebytes.js";
import {
  describeCrop,
  parseCropSpec,
  resolveCropRect,
  type CropRect,
  type CropSpec,
} from "./crop.js";
import { describeError, BananaError } from "./errors.js";
import { hasQuota, quotaStatus, recordUsage } from "./state.js";

type TextContent = { type: "text"; text: string };
type ImageContent = { type: "image"; data: string; mimeType: string };
type ToolResult = { content: (TextContent | ImageContent)[]; isError?: boolean };

/** The seams the tools depend on, so tests can drive the server without a browser. */
export interface ImageProvider {
  generate(request: GenerateRequest): Promise<CaptureResult>;
  ensureReady(): Promise<unknown>;
}

export interface ImageOps {
  readonly isOpen: boolean;
  makePreview(buf: Buffer, mimeType: string): Promise<string | null>;
  cropImage(buf: Buffer, mimeType: string, rect: CropRect): Promise<Buffer | null>;
}

export interface ServerDeps {
  provider: ImageProvider;
  session: ImageOps;
  queue: SerialQueue;
}

function defaultDeps(): ServerDeps {
  const session = new BrowserSession();
  return {
    session,
    provider: new AiStudioProvider(session),
    queue: new SerialQueue(config.pacingMs),
  };
}

/**
 * Travels with every successful result. Cropping removes a visible mark but not
 * SynthID, so an agent handing the file onward should still know what it is.
 */
const PROVENANCE_NOTE =
  "Provenance: AI-generated by Gemini; contains an invisible SynthID watermark.";

function errorResult(err: unknown): ToolResult {
  const info = describeError(err);
  const lines = [`[${info.kind}] ${info.message}`];
  if (info.hint) lines.push(`Hint: ${info.hint}`);
  if (info.debugPath) lines.push(`Debug dump: ${info.debugPath}`);
  return { content: [{ type: "text", text: lines.join("\n") }], isError: true };
}

function describeSaved(saved: SavedImage[]): string {
  return saved
    .map((image, index) => {
      const dims = image.width && image.height ? `${image.width}x${image.height}` : "unknown size";
      return `${index + 1}. ${image.path} (${dims}, ${image.format}, ${Math.round(image.bytes / 1024)} KB)`;
    })
    .join("\n");
}

/**
 * Trims the requested inset off an image, re-encoding losslessly as PNG. A crop that
 * cannot be performed leaves the image untouched and says so, rather than losing it.
 */
async function applyCrop(
  deps: ServerDeps,
  buf: Buffer,
  spec: CropSpec | null,
  notes: string[],
): Promise<Buffer> {
  if (!spec) return buf;

  const format = sniffFormat(buf);
  const dims = readDimensions(buf);
  if (!format || !dims) {
    notes.push("Crop skipped: could not read image dimensions.");
    return buf;
  }

  let rect: CropRect | null;
  try {
    rect = resolveCropRect(spec, dims.width, dims.height);
  } catch (err) {
    throw BananaError.invalidInput(err instanceof Error ? err.message : String(err));
  }
  if (!rect) return buf;

  const cropped = await deps.session.cropImage(buf, mimeFor(format), rect);
  if (!cropped) {
    notes.push("Crop failed in the browser; saved the uncropped image instead.");
    return buf;
  }
  notes.push(`Crop: ${describeCrop(rect, dims)}.`);
  return cropped;
}

async function runGeneration(
  deps: ServerDeps,
  args: {
    prompt: string;
    count: number;
    aspectRatio?: string;
    imagePaths?: string[];
    outputPath?: string;
    inline: boolean;
    reuseConversation: boolean;
    crop?: string;
  },
): Promise<ToolResult> {
  // Parsed before the generation so a typo costs no quota.
  let cropSpec: CropSpec | null;
  try {
    cropSpec = parseCropSpec(args.crop ?? config.crop);
  } catch (err) {
    throw BananaError.invalidInput(err instanceof Error ? err.message : String(err));
  }

  if (!(await hasQuota(args.count))) {
    const { used, limit } = await quotaStatus();
    throw BananaError.quotaExhausted(used, limit);
  }

  const { images, text } = await deps.provider.generate({
    prompt: args.prompt,
    count: args.count,
    aspectRatio: args.aspectRatio,
    imagePaths: args.imagePaths,
    reuseConversation: args.reuseConversation,
  });

  const notes: string[] = [];
  const finalImages: Buffer[] = [];
  for (const buf of images) {
    finalImages.push(await applyCrop(deps, buf, cropSpec, notes));
  }

  const saved: SavedImage[] = [];
  for (const [index, buf] of finalImages.entries()) {
    saved.push(
      await saveImage(buf, args.prompt, {
        outputPath: args.outputPath,
        index,
        total: finalImages.length,
      }),
    );
  }
  await recordUsage(images.length);
  const quota = await quotaStatus();

  const content: (TextContent | ImageContent)[] = [
    {
      type: "text",
      text: [
        `Generated ${saved.length} image${saved.length === 1 ? "" : "s"}:`,
        describeSaved(saved),
        notes.length > 0 ? notes.join("\n") : null,
        PROVENANCE_NOTE,
        `Quota (local estimate): ${quota.used}/${quota.limit} used today, ${quota.remaining} left.`,
        text ? `Model said: ${text.slice(0, 300)}` : null,
      ]
        .filter(Boolean)
        .join("\n"),
    },
  ];

  // Full-size base64 only on request; otherwise a small preview so the calling
  // model can see the result without megabytes of context.
  for (const [index, buf] of finalImages.entries()) {
    const format = saved[index]!.format;
    if (args.inline) {
      content.push({ type: "image", data: buf.toString("base64"), mimeType: mimeFor(format) });
      continue;
    }
    const preview = await deps.session.makePreview(buf, mimeFor(format));
    if (preview) content.push({ type: "image", data: preview, mimeType: "image/jpeg" });
  }

  return { content };
}

export function createServer(deps: ServerDeps = defaultDeps()): McpServer {
  const server = new McpServer(
    { name: "banana-bridge", version: "0.1.0" },
    {
      instructions:
        "Generates and edits images with Gemini by driving the AI Studio web UI in a real browser. " +
        "Requires a one-time `npx banana-bridge login`. Requests are processed one at a time. " +
        "All images returned by this server are AI-generated and carry Google's SynthID, an " +
        "invisible in-pixel watermark that survives cropping, resizing and re-encoding. Preserve " +
        "that provenance if you pass these images on.",
    },
  );

  server.registerTool(
    "generate_image",
    {
      title: "Generate image",
      description:
        "Generate an image from a text prompt using Gemini's image model via the AI Studio web UI. " +
        "Saves to disk and returns the file path plus a small preview. Output is AI-generated and " +
        "carries an invisible SynthID watermark.",
      inputSchema: {
        prompt: z.string().min(1).describe("What to draw. Be specific about subject, style and composition."),
        aspect_ratio: z
          .enum(["1:1", "3:4", "4:3", "9:16", "16:9"])
          .optional()
          .describe("Requested aspect ratio; passed to the model as part of the prompt."),
        count: z.number().int().min(1).max(4).default(1).describe("How many images to ask for (1-4)."),
        output_path: z.string().optional().describe("Absolute path to write to. Defaults to the configured output dir."),
        inline: z
          .boolean()
          .default(false)
          .describe("Return the full-resolution image as base64 instead of a downscaled preview."),
        crop: z
          .string()
          .optional()
          .describe(
            'Trim insets off the result, losslessly. "auto" removes the bottom strip where ' +
              'the Gemini app stamps its visible mark; also accepts "bottom:6%", "48px", or ' +
              '"top,right,bottom,left". Defaults to BANANA_CROP.',
          ),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async (args): Promise<ToolResult> =>
      deps.queue
        .run(() =>
          runGeneration(deps, {
            prompt: args.prompt,
            count: args.count ?? 1,
            aspectRatio: args.aspect_ratio,
            outputPath: args.output_path,
            inline: args.inline ?? false,
            crop: args.crop,
            reuseConversation: false,
          }),
        )
        .catch(errorResult),
  );

  server.registerTool(
    "edit_image",
    {
      title: "Edit image",
      description:
        "Edit or combine existing local images with a text instruction. The images are uploaded into the " +
        "AI Studio chat and the edited result is saved to disk. Output is AI-generated and carries an " +
        "invisible SynthID watermark.",
      inputSchema: {
        prompt: z.string().min(1).describe("The edit instruction, e.g. 'make the sky stormy'."),
        image_paths: z
          .array(z.string())
          .min(1)
          .max(4)
          .describe("Absolute paths of local images to upload as input."),
        output_path: z.string().optional().describe("Absolute path to write the result to."),
        inline: z.boolean().default(false).describe("Return full-resolution base64 instead of a preview."),
        crop: z
          .string()
          .optional()
          .describe(
            'Trim insets off the result, losslessly. "auto" removes the bottom strip where ' +
              'the Gemini app stamps its visible mark; also accepts "bottom:6%", "48px", or ' +
              '"top,right,bottom,left". Defaults to BANANA_CROP.',
          ),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async (args): Promise<ToolResult> =>
      deps.queue
        .run(() =>
          runGeneration(deps, {
            prompt: args.prompt,
            count: 1,
            imagePaths: args.image_paths,
            outputPath: args.output_path,
            inline: args.inline ?? false,
            crop: args.crop,
            reuseConversation: false,
          }),
        )
        .catch(errorResult),
  );

  server.registerTool(
    "session_status",
    {
      title: "Session status",
      description:
        "Report whether the browser session is signed in, the local daily-quota estimate, and current queue depth.",
      inputSchema: {},
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    async (): Promise<ToolResult> => {
      const quota = await quotaStatus();
      const lines = [
        `Browser: ${deps.session.isOpen ? "running" : "not started"} (headless=${config.headless})`,
        `Model: ${config.model}`,
        `Profile: ${config.profileDir}`,
        `Output dir: ${config.outputDir}`,
        `Default crop: ${config.crop}`,
        `Quota (local estimate): ${quota.used}/${quota.limit} used on ${quota.day}, ${quota.remaining} left.`,
        `Queue depth: ${deps.queue.depth}`,
      ];
      try {
        await deps.queue.run(() => deps.provider.ensureReady());
        lines.unshift("Signed in: yes");
      } catch (err) {
        const info = describeError(err);
        lines.unshift(`Signed in: no (${info.kind}: ${info.message})`);
        if (info.hint) lines.push(`Hint: ${info.hint}`);
      }
      return { content: [{ type: "text", text: lines.join("\n") }] };
    },
  );

  return server;
}

export async function serve(): Promise<void> {
  const session = new BrowserSession();
  const deps: ServerDeps = {
    session,
    provider: new AiStudioProvider(session),
    queue: new SerialQueue(config.pacingMs),
  };
  const server = createServer(deps);
  const transport = new StdioServerTransport();
  await server.connect(transport);

  const shutdown = async () => {
    await session.close();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  process.stdin.on("close", shutdown);
}
